In [1]:
random.rand(100)

NameError: name 'random' is not defined

In [26]:
import numpy as np
import time
alist = np.random.rand(1000000)
blist = np.random.rand(1000000)
c =0
tic = time.time()

c=np.dot(alist,blist)
toc = time.time()
print c
print "Time in MS vectorized", str(1000*(toc - tic))

c=0
tic = time.time()
for i in range(1000000):
    c += alist[i] * blist[i]
toc = time.time()
print c
print "Time in MS ", str(1000*(toc - tic))

250068.003225
Time in MS vectorized 1.20997428894
250068.003225
Time in MS  714.2598629


In [7]:
import numpy as np
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print c


[[ 0.86666572 -0.52915543  0.46464143]
 [ 0.32714512 -0.45289655 -0.08599313]
 [ 0.53254504  1.95866926  2.30748757]]


In [ ]:
import numpy as np